# Generated by Django 4.2.13 on 2024-07-01 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('created_by_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='RoleLkp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by_date', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_lkp',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='user_identity_service.rolelkp'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
