# Generated by Django 4.2.13 on 2024-07-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_identity_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IsActive',
            field=models.BooleanField(default=True),
        ),
    ]
