# Generated by Django 4.2.13 on 2024-07-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_identity_service', '0002_user_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='IsActive',
            new_name='is_active',
        ),
    ]
