# Generated by Django 4.2.13 on 2024-07-01 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageLkp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=100, unique=True)),
                ('language_abbreviation', models.CharField(max_length=2, unique=True)),
                ('created_by', models.UUIDField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField()),
                ('updated_by_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'language_lkp',
            },
        ),
    ]
