# Generated by Django 5.0.6 on 2024-07-04 07:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('original_folder_url', models.CharField(max_length=255)),
                ('translated_folder_url', models.CharField(max_length=255)),
                ('review_folder_url', models.CharField(max_length=255)),
                ('created_by', models.UUIDField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'ad_group',
            },
        ),
        migrations.CreateModel(
            name='FileTypeLkp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=100, unique=True)),
                ('created_by', models.UUIDField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'file_type_lkp',
            },
        ),
        migrations.CreateModel(
            name='StatusLkp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100, unique=True)),
                ('created_by', models.UUIDField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'status_lkp',
            },
        ),
        migrations.CreateModel(
            name='TranslationActionLkp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100, unique=True)),
                ('created_by', models.UUIDField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'translation_action_lkp',
            },
        ),
        migrations.CreateModel(
            name='TranslationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('translator_user_id', models.UUIDField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_date', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'translation_batch',
            },
        ),
        migrations.AlterField(
            model_name='languagelkp',
            name='updated_by',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='languagelkp',
            name='updated_by_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='AdGroupUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('created_by', models.UUIDField()),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_date', models.DateTimeField(null=True)),
                ('ad_group_id', models.ForeignKey(db_column='ad_group_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.adgroup')),
            ],
            options={
                'db_table': 'ad_group_user',
            },
        ),
        migrations.CreateModel(
            name='Glossary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department_lkp_id', models.UUIDField()),
                ('file_blob_path', models.CharField(max_length=255)),
                ('created_by', models.UUIDField()),
                ('created_by_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('updated_by_datetime', models.DateTimeField(null=True)),
                ('language_lkp_id', models.ForeignKey(db_column='language_lkp_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.languagelkp')),
            ],
            options={
                'db_table': 'glossary',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviewer_user_id', models.UUIDField(unique=True)),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('due_date', models.DateTimeField()),
                ('source_file_blob_path', models.CharField(max_length=255)),
                ('translated_file_blob_path', models.CharField(max_length=255)),
                ('reviewed_file_blob_path', models.CharField(max_length=255)),
                ('translation_feedback', models.CharField(max_length=500)),
                ('sharepoint_source_file_path', models.CharField(max_length=255)),
                ('sharepoint_target_file_path', models.CharField(max_length=255)),
                ('ad_group_id', models.ForeignKey(db_column='ad_group_id', on_delete=django.db.models.deletion.PROTECT, related_name='ad_group', to='requester_service.adgroup')),
                ('file_type_lkp_id', models.ForeignKey(db_column='file_type_lkp_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.filetypelkp')),
                ('glossary_id', models.ForeignKey(db_column='glossary_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.glossary')),
                ('source_language_id', models.ForeignKey(db_column='base_language_id', on_delete=django.db.models.deletion.PROTECT, related_name='source_language', to='requester_service.languagelkp')),
                ('status_lkp_id', models.ForeignKey(db_column='status_lkp_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.statuslkp')),
                ('target_language_id', models.ForeignKey(db_column='translate_language_id', on_delete=django.db.models.deletion.PROTECT, related_name='target_language', to='requester_service.languagelkp')),
                ('translation_batch_id', models.ForeignKey(db_column='translation_batch_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.translationbatch')),
            ],
            options={
                'db_table': 'translation',
            },
        ),
        migrations.CreateModel(
            name='Translation_log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_by_user_id', models.UUIDField()),
                ('action_datetime', models.DateTimeField(auto_now_add=True)),
                ('translation_id', models.ForeignKey(db_column='translation_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.translation')),
                ('translation_action_lkp_id', models.ForeignKey(db_column='translation_action_lkp_id', on_delete=django.db.models.deletion.PROTECT, to='requester_service.translationactionlkp')),
            ],
            options={
                'db_table': 'translation_log',
            },
        ),
    ]
